SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%subsidise_trus%'

--CÁCH KIỂM TRA THÔNG TIN CỘT TRONG MỖI BẢNG TRONG DATABASE 

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME like '%ln_contract%'